name: Full Stack CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: |
            backend/package-lock.json
            frontend/package-lock.json

      # -------- BACKEND --------
      - name: Install Backend Dependencies
        working-directory: Backend
        run: npm ci

      - name: Build Backend
        working-directory: Backend
        run: npm run build --if-present

      # -------- FRONTEND --------
      - name: Install Frontend Dependencies
        working-directory: Frontend
        run: npm ci

      - name: Build Frontend
        working-directory: Frontend
        run: npm run build --if-present

      # -------- DEPLOY --------
      - name: Deploy Backend
        run: curl -X POST "${{ secrets.BACKEND_HOOK }}"

      - name: Deploy Frontend
        run: curl -X POST "${{ secrets.FRONTEND_HOOK }}"
